### ISSUE TITLE
Hi help Requests

### ISSUE THREAD

**Issue by cold-hr** [llchrisll/lllchrislll-scripts#1]
I want you to customize the script.
https://github.com/rathena/rathena/blob/master/npc/custom/woe_controller.txt

Want a menu For customization Castle
Set class1 / class 2 / hiclass / 3rd class.
And the status as status 255/355/455 and so on.

thank you so much.

**Comment by llchrisll** [comment]
@cold-hr I'm sorry, but I only do modifications at my own scripts.
If you want to modify an rAthena script, please use the rAthena Forum and ask there.

**Comment by cold-hr** [comment]
thank
