### ISSUE TITLE
Hunting grounds Instance not working

### ISSUE THREAD

**Issue by AsurielRO** [llchrisll/lllchrislll-scripts#11]
After i use the yml files for hunting ground i can't see any error on the console.

but in-game process i can't enter the instance and it said "Instance creation failed".

I've check quest_db.yml and intance_db.yml i think everything was fine.

The main issue as far as i know is the instance ID.

**Comment by llchrisll** [comment]
To be hontest I can't really remember if I tested this after I made the yml conversion, I think I did tho, gonna check it....

**Comment by llchrisll** [comment]
So I just tested it and it works fine :I.
No issue at all.
