### ISSUE TITLE
Equipment Enchanter 

### ISSUE THREAD

**Issue by smallvill3** [llchrisll/lllchrislll-scripts#13]
Hi. your Equipment Enchanter works perfectly nice.
Thanks for your masterpiece script.

Just a small request, can you add item + zeny required too?
Also, how to add specialeffect for both success effect and failed upgrade?
It runs both effect when i add those.
- specialeffect 154;
- specialeffect 155;

Thanks in advance.

**Comment by llchrisll** [comment]
Sorry, for the late reply, I just noticed it lol...
I will not make any modifications to my scripts anymore.
