### ISSUE TITLE
Arena Master Error

### ISSUE THREAD

**Issue by AsurielRO** [llchrisll/lllchrislll-scripts#4]
Got error when choosing a map.

![image](https://user-images.githubusercontent.com/29746866/60263342-0216fc80-9913-11e9-9d8b-2251e535bafb.png)

**Comment by llchrisll** [comment]
Okay, thanks for the report, I will look into it. Any other error? Or information to reproduce it?

**Comment by AsurielRO** [comment]
no other error aside from that, i just disable the announce message into the script i think that part is the problem.

**Comment by llchrisll** [comment]
Well I kinda messed the "mapannounce" lines up, not sure why I didn't test that after I changed it.
But I will test it soon, made the changes so far, but didn't have any time yet or rather motivation to fix it.

**Comment by llchrisll** [comment]
So easy fix, will update it soon:
Exchange bc_all|bc_red; with bc_all,0xFF0000; at the mapannounces.
That's all lol.

Edit: Fixed in 63d39601adbe5a07a03c522c160ecdb246419229
