### ISSUE TITLE
Hunting Grounds

### ISSUE THREAD

**Issue by AsurielRO** [llchrisll/lllchrislll-scripts#5]
Always got a couple of debug on my emulator when killing a monsetr inside the instance

![image](https://user-images.githubusercontent.com/29746866/60263451-473b2e80-9913-11e9-9e2a-dbbda2fe11ef.png)

**Comment by llchrisll** [comment]
Don't worry, just a debugmes I forgot to delete. You can ignore it.

**Comment by llchrisll** [comment]
Fixed in 63d39601adbe5a07a03c522c160ecdb246419229
