### ISSUE TITLE
OGH with hard mode

### ISSUE THREAD

**Issue by AsurielRO** [llchrisll/lllchrislll-scripts#7]
First normal mode at the second floor going thru 3rd floor amdarias the monsters inside it should be scattered around the map each portal, like khalitzburg knight etc. second the dialog of the npc ais too long while the portal is already open even the npc's not finish to talk, after you killed amdarias and enter another instance for hard mode we will get this error

and after killing 5 to 6 mobs the 2nd knight mvp boss automatically appeared it should be appeared after killing a couple of monsters.

![image](https://user-images.githubusercontent.com/29746866/60929474-10d2bb80-a2e4-11e9-9e7a-c34e492ec948.png)

**Comment by AsurielRO** [comment]
My bad you need to recreate a party before you enter OGH Hard mode, but same the error should be fixed

**Comment by AsurielRO** [comment]
and maybe the portal on the second floor is open because im using GM Account?

**Comment by AsurielRO** [comment]
Hard mode : Missing Contaminated Magic Spell drop item, same as normal mode the monster inside the second floor should be scattered and the portal still open even the npc's still not finish talking.

**Comment by AsurielRO** [comment]
OGH Hard mode doesn't summon all hard mode mobs even the amdarias still the color red not the green one.

i think that's all the problem

**Comment by AsurielRO** [comment]
Last thing can't enter the hidden treasure after killing amdarias both normal and hard mode
![image](https://user-images.githubusercontent.com/29746866/60930177-049c2d80-a2e7-11e9-89a5-3e521d0a60cc.png)

**Comment by AsurielRO** [comment]
i also use jump to check the hidden treasures but the crack doesn't drop anything
![image](https://user-images.githubusercontent.com/29746866/60930211-331a0880-a2e7-11e9-9db5-d9e7c823b1b5.png)

**Comment by llchrisll** [comment]
I basically only exchanged the mob ids with their hard ones, didn't change anything with their spawns.
Also I didn't check the treasure room.
About the portal, that's as far as I know also in the normal one like this. At least in rAthena.
The item Contanimated Magic should be dropped by the monsters added to the mob_db2.txt.
I tested that and I'm sure they were added.

**Comment by AsurielRO** [comment]
hmmmm it seems like its not working on my side maybe need a full server restart?

**Comment by llchrisll** [comment]
reloadscript and reloadmobdb should be fine, maybe reloadinstancedb too

**Comment by AsurielRO** [comment]
@llchrisll i already try the reloadmobdb should be fine, maybe reloadinstancedb also recompile server even not change

its generating the normal mode instance even i choose hard mode also the monsters inside hard mode is still on normal mode.

**Comment by llchrisll** [comment]
Found the problem > Solved in 284f93d3a0a2471cab1877f5a82725c2cb481619
